### PR TITLE
Refactor to use context and reducer

### PR DESCRIPTION
**Pull request by ChinyangaTL**

### CODE REVIEW

**Comment by ChinyangaTL** [comment]
Just noticed the merge conflict. 
After resolving it I was met only with an option to commit the merge.

I chose note too. It's a simple solution. Just keep the README.md that is currently in the master. The one from develop can all go. Hope that makes sense.

**Comment by ChinyangaTL** [comment]
So after I realized I made a monumental cock up with file structure and placing of state values, rather than doing painful state uplifting I decided to refactor the entire application to useContext and useReducer.

Also implemented:
- a draw state for the game
- few minor bug fixes

**Comment by rmoswela** [comment]
improve on the utilization of feature branches and try adding release branch for when you start getting the ci/cd pipeline going. I want you to utilize the whole of the git flow so you get into rhythm before sprints.

Nice commit messages.

I will check the code this weekend

Fix the conflicts

**Comment by ChinyangaTL** [comment]
> improve on the utilization of feature branches and try adding release branch for when you start getting the ci/cd pipeline going. I want you to utilize the whole of the git flow so you get into rhythm before sprints.
> noted ✔️  
> Nice commit messages.
> Thank you, I good teacher.🙇 
> I will check the code this weekend
> 👍 
> Fix the conflicts
> 👍

**Comment by ChinyangaTL** [comment]
@rmoswela Resolved the conflict in the read me files.
Every is green for pushing 🚀

**Comment by rmoswela** [comment]
Great job my guy 🙌🏾🙌🏾

**Pull request merged**
